services:
  fq-server:
    depends_on:
      - mongodb
    build:
      context: .
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    command: --quiet
volumes:
  mongodb_data_container: